# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # For Python dependencies in Django
    directory: "server/" # Location of package manifests for backend
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm" # For Node.js dependencies in Next.js
    directory: "client/" # Location of package manifests for frontend
    schedule:
      interval: "monthly"
